# From:
#  https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
#  https://github.com/denoland/dnt
#  https://github.com/marketplace/actions/install-deno

name: NPM Package

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag not containing /

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno -V
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: npm build
        run: deno run -A "./scripts/build-npm.ts" ${{steps.get_tag_version.outputs.TAG_VERSION}}
      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd npm && npm publish
